spring.application.name=webapplication
server.port=${PORT:8081}
#DATABASE CONFIGURATION
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/webapplication?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Meraj@12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#HIBERNATE / JPA CONFIGURATION (Table Auto-Generation)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#CUSTOM JWT SECURITY CONFIGURATION
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.google.client-id=198939374677-2ua306rncfr6u4upkhj7finmte2cg8lo.apps.googleusercontent.com

# Google Gemini AI Configuration
gemini.api.key=${GEMINI_API_KEY}

# Admin configuration (comma-separated emails)
application.security.admin-emails=${ADMIN_EMAILS:}

